[package]
name = "voyager-resolver-cairo-2-6-3"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
starknet.workspace = true
indoc.workspace = true
itertools.workspace = true
salsa = "0.16.1"
scarb-metadata.workspace = true
serde.workspace = true
serde_json.workspace = true
smol_str.workspace = true
tracing = "0.1.37"
regex = "1.7.1"
petgraph = "0.5.0"
toml.workspace = true
toml_edit = "0.19.8"
rstest = "0.17.0"
camino.workspace = true
dyn-compiler = { path = "../dyn-compiler" }

# All version dependent dependencies
cairo-lang-compiler = "2.6.3"
cairo-lang-defs = "2.6.3"
cairo-lang-diagnostics = "2.6.3"
cairo-lang-filesystem = "2.6.3"
cairo-lang-parser = "2.6.3"
cairo-lang-semantic = "2.6.3"
cairo-lang-starknet = "2.6.3"
cairo-lang-syntax = "2.6.3"
cairo-lang-utils = "2.6.3"

scarb = { git = "https://github.com/software-mansion/scarb", tag = "v2.6.4" }
scarb-ui = { git = "https://github.com/software-mansion/scarb", tag = "v2.6.4" }
deno_task_shell = "0.15.0" # Patch for scarb v2.6.4

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-case = "2.2.2"
test-case-macros = "2.2.2"
test-log.workspace = true
