name: Crates.io Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.ref }}
      fail-fast: true

  build_binaries:
    needs: test
    name: Build release binaries
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.ref_name }}

  publish_crate:
    needs: [test, build_binaries]
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Verify version in Cargo.toml
        run: |
          CARGO_VERSION=$(grep -m 1 'version =' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
          echo "Cargo.toml version: $CARGO_VERSION"
          echo "Release version: ${{ steps.get_version.outputs.version }}"
          if [ "$CARGO_VERSION" != "${{ steps.get_version.outputs.version }}" ]; then
            echo "Error: Version in Cargo.toml ($CARGO_VERSION) does not match release version (${{ steps.get_version.outputs.version }})"
            exit 1
          fi
      
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_binaries, publish_crate]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            
            ## Installation
            
            ### From binaries
            Download the appropriate binary for your platform from the assets below.
            
            ### From crates.io
            ```bash
            cargo install starknet-contract-verifier
            ```
            
            ## What's Changed
            
            See the [changelog](https://github.com/${{ github.repository }}/compare/${{ github.ref_name }}...HEAD) for details.
          files: |
            artifacts/build-*/starknet-contract-verifier-*
            artifacts/checksums/checksums.sha256
          draft: false
          prerelease: false