name: Crates.io Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Verify version in Cargo.toml
        run: |
          CARGO_VERSION=$(grep -m 1 'version =' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
          echo "Cargo.toml version: $CARGO_VERSION"
          echo "Release version: ${{ steps.get_version.outputs.version }}"
          if [ "$CARGO_VERSION" != "${{ steps.get_version.outputs.version }}" ]; then
            echo "Error: Version in Cargo.toml ($CARGO_VERSION) does not match release version (${{ steps.get_version.outputs.version }})"
            exit 1
          fi
      
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} 