name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: starknet-contract-verifier
            asset_name: starknet-contract-verifier-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: starknet-contract-verifier
            asset_name: starknet-contract-verifier-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: starknet-contract-verifier
            asset_name: starknet-contract-verifier-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: starknet-contract-verifier
            asset_name: starknet-contract-verifier-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: starknet-contract-verifier.exe
            asset_name: starknet-contract-verifier-windows-amd64.exe

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install cross-compilation tools (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          if-no-files-found: error

  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Upload Linux AMD64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./starknet-contract-verifier-linux-amd64/starknet-contract-verifier
          asset_name: starknet-contract-verifier-linux-amd64
          asset_content_type: application/octet-stream
          
      - name: Upload Linux ARM64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./starknet-contract-verifier-linux-arm64/starknet-contract-verifier
          asset_name: starknet-contract-verifier-linux-arm64
          asset_content_type: application/octet-stream
          
      - name: Upload macOS AMD64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./starknet-contract-verifier-macos-amd64/starknet-contract-verifier
          asset_name: starknet-contract-verifier-macos-amd64
          asset_content_type: application/octet-stream
          
      - name: Upload macOS ARM64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./starknet-contract-verifier-macos-arm64/starknet-contract-verifier
          asset_name: starknet-contract-verifier-macos-arm64
          asset_content_type: application/octet-stream
          
      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./starknet-contract-verifier-windows-amd64.exe/starknet-contract-verifier.exe
          asset_name: starknet-contract-verifier-windows-amd64.exe
          asset_content_type: application/octet-stream 