name: release
on:
  push:
    branches:
      - nothing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -  run: echo "implement this"

# TODO: To add more, supposingly CI should run build, and CD(this ci) should run release.
# Ideally we should have a comprehensive CD to push to crates.io